/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-05-06 02:43:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class calendar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1493827749187L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>My JSP 'index.jsp' starting page</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../css/base.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../skins/all.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- <link href=\"../css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\" /> -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../img/title.ico\" type=\"image/x-icon\"/>\r\n");
      out.write("<style>\r\n");
      out.write("\t.btn.dropdown-toggle{\r\n");
      out.write("\t\tbackground:#CCCCCC;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxfileupload.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxSubmit.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"../js/Carousel.js\"></script>\r\n");
      out.write("<script src=\"../js/jquery.icheck.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.min.js\"></script>\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"../js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/locales/bootstrap-datetimepicker.zh-CN.js\"></script> -->\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction upload() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"register/firm.do\", // 自行按需配置好完整的url，包括ip和端口号  \r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdatatype : \"text\",\r\n");
      out.write("\t\t\tdata : JSON.stringify($(\"#form1\").serializeObject()),\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//头部\r\n");
      out.write("\tfunction changeColor1(der){\r\n");
      out.write("\t\tder.style.background=\"#777777\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor2(der){\r\n");
      out.write("\t\tder.style.background=\"#32373C\";\r\n");
      out.write("\t}\r\n");
      out.write("\tjQuery(function($){\r\n");
      out.write("\t\t$(\".dropdown .form-control\").click(function(){\r\n");
      out.write("\t\t\tif(this.parentNode.getElementsByTagName(\"button\") == undefined){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tthis.parentNode.getElementsByTagName(\"button\")[0].click();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"http://www.helloweba.com/demo/css/main.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/fullcalendar.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/fancybox.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#calendar{width:960px; margin:20px auto 10px auto}\r\n");
      out.write("\t.fancy{width:450px; height:auto}\r\n");
      out.write("\t.fancy h3{height:30px; line-height:30px; border-bottom:1px solid #d3d3d3; font-size:14px}\r\n");
      out.write("\t.fancy form{padding:10px}\r\n");
      out.write("\t.fancy p{height:28px; line-height:28px; padding:4px; color:#999}\r\n");
      out.write("\t.input{height:20px; line-height:20px; padding:2px; border:1px solid #d3d3d3; width:100px}\r\n");
      out.write("\t.btn{-webkit-border-radius: 3px;-moz-border-radius:3px;padding:5px 12px; cursor:pointer}\r\n");
      out.write("\t.btn_ok{background: #360;border: 1px solid #390;color:#fff}\r\n");
      out.write("\t.btn_cancel{background:#f0f0f0;border: 1px solid #d3d3d3; color:#666 }\r\n");
      out.write("\t.btn_del{background:#f90;border: 1px solid #f80; color:#fff }\r\n");
      out.write("\t.sub_btn{height:32px; line-height:32px; padding-top:6px; border-top:1px solid #f0f0f0; text-align:right; position:relative}\r\n");
      out.write("\t.sub_btn .del{position:absolute; left:2px}\r\n");
      out.write("\t.circleA {\r\n");
      out.write("\t    width: 22px;\r\n");
      out.write("\t    height: 22px;\r\n");
      out.write("\t    background: #00B38A;\r\n");
      out.write("\t    -moz-border-radius: 5px;\r\n");
      out.write("\t    -webkit-border-radius: 5px;\r\n");
      out.write("\t    border-radius: 22px;\r\n");
      out.write("\t    padding:4px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.triangle-left1 {\r\n");
      out.write("\t\twidth: 0;\r\n");
      out.write("\t\theight: 0;\r\n");
      out.write("\t\tborder-top: 7px solid transparent;\r\n");
      out.write("\t\tborder-bottom: 7px solid transparent;\r\n");
      out.write("\t\tborder-right: 10px solid #FFF;\r\n");
      out.write("\t}\r\n");
      out.write("\t.triangle-right {\r\n");
      out.write("\t\twidth: 0;\r\n");
      out.write("\t\theight: 0;\r\n");
      out.write("\t\tborder-top: 7px solid transparent;\r\n");
      out.write("\t\tborder-bottom: 7px solid transparent;\r\n");
      out.write("\t\tborder-left: 10px solid #FFF;\r\n");
      out.write("\t}\r\n");
      out.write("\t.clicking-test {\r\n");
      out.write("\t\tbackground: #AADDFF;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- <script src='../js/jquery-1.9.1.js'></script> -->\r\n");
      out.write("<!-- <script src='http://code.jquery.com/ui/1.10.3/jquery-ui.js'></script> -->\r\n");
      out.write("<script src='../js/fullcalendar.min.js'></script>\r\n");
      out.write("<script src='../js/jquery.fancybox-1.3.1.pack.js'></script>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\t//头部\r\n");
      out.write("\tfunction changeColor1(der){\r\n");
      out.write("\t\tder.style.background=\"#777777\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor2(der){\r\n");
      out.write("\t\tder.style.background=\"#32373C\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor3(der){\r\n");
      out.write("\t\tder.style.background=\"#00B38A\";\r\n");
      out.write("\t\tder.style.color=\"#FFF\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor4(der){\r\n");
      out.write("\t\tder.style.background=\"#FFF\";\r\n");
      out.write("\t\tder.style.color=\"#000\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction selectInterviewType(seqno){\r\n");
      out.write("\t\ttop.location.href=\"user_view.jsp?\"+seqno;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction init() {\r\n");
      out.write("\t\tvar url = \"firm/userviewPage1.do\";\r\n");
      out.write("\t\tvar formId = \"userviewForm\";\r\n");
      out.write("\t\tvar data = ajaxSumbit(url, formId);\r\n");
      out.write("\t\tdocument.getElementById('type111').innerText = \"等待候选人回应(\"+data.interview1+\")\";\r\n");
      out.write("\t\tdocument.getElementById('type222').innerText = \"待安排面试(\"+data.interview2+\")\";\r\n");
      out.write("\t\tdocument.getElementById('type333').innerText = \"待反馈结果(\"+data.interview3+\")\";\r\n");
      out.write("\t\tdocument.getElementById('type444').innerText = \"面试通过(\"+data.interview4+\")\";\r\n");
      out.write("\t\tdocument.getElementById('type555').innerText = \"归档(\"+data.interview5+\")\";\r\n");
      out.write("\t\tdocument.getElementById('userName').innerText = data.userName;\r\n");
      out.write("\t\t//document.getElementById(\"type1\").setAttribute(\"class\",\"greenTd\");\r\n");
      out.write("\t\t//goSearch();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction weekWrite(weekDay, dayNum){\r\n");
      out.write("\t\tvar a = dayNum + 1;\r\n");
      out.write("\t\t/* dayNum = dayNum.replace(\"\\n\",\"\");\r\n");
      out.write("\t\tdayNum = dayNum.replace(\"\\r\",\"\");\r\n");
      out.write("\t\tdayNum = dayNum.replace(\"<br>\",\"\");\r\n");
      out.write("\t\tdayNum = dayNum.replace(\" \",\"\"); */\r\n");
      out.write("\t\tdocument.getElementById(\"dayNum\").innerText=dayNum;\r\n");
      out.write("\t\tdocument.getElementById(\"weekName\").innerText=\"星期\"+weekDay;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction adddiv(items){\r\n");
      out.write("\t\tvar div1 = \"\";\r\n");
      out.write("\t\tfor(var i in items){\r\n");
      out.write("\t\t\tdiv1 = div1 + \"<div style='width:100%;border-bottom:1px #CCCCCC solid;'>\"\r\n");
      out.write("\t\t\t\t\t\t\t+ \"<table style='width:100%;border-collapse:separate;border-spacing:15px;'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"<td width='40%' rowspan='5' valign='top'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"<font id='oclock' color='#00B38A' style='font-size:14px;'>\"+items[i].time+\"</font>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"<td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"<font id='username' style='font-size:14px;' color='#4F4F4F'>\"+items[i].name+\"</font>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"<td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"<font color='#9A9A9A' style='font-size:14px;'>职位</font>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"<td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"<font id='job' style='font-size:14px;' color='#4F4F4F'>\"+items[i].job+\"</font>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"<td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"<font color='#9A9A9A' style='font-size:14px;'>联系方式</font>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"<td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"<font id='phone' style='font-size:14px;' color='#4F4F4F'>\"+items[i].phone+\"</font>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"<td colspan='2' class='textC'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"<button type='button' class='btn btn-primary' onclick='validateCode(\\\"\"+items[i].id+\"\\\")'\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"style='background-color:#FFF;border-color:#00B38A;width:100px;'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ \"<font style='font-size:14px;' color='#00B38A' style='border-radius:40px;'>下载简历</font>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"</button>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t+ \"</table>\"\r\n");
      out.write("\t\t\t\t\t\t+ \"</div>\"\r\n");
      out.write("\t\t\t\t\t\t+ \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(\"interviewContent\").innerHTML = div1;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction validateCode(str) {\r\n");
      out.write("\t\ttop.location.href='../user/downloadPdf2.do?str=' + str;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tdocument.getElementById(\"interviewContent\").innerHTML = \"\";\r\n");
      out.write("\t\t$('#calendar').fullCalendar({\r\n");
      out.write("\t\t\t//console.log(this);\r\n");
      out.write("\t\t\theader: {\r\n");
      out.write("\t\t\t\tleft: 'prev,title,next',\r\n");
      out.write("\t\t\t\tcenter: '',\r\n");
      out.write("\t\t\t\tright: ''\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tevents:  {\r\n");
      out.write("                url: \"/hibernateMvc/test/calenderTest.do\",\r\n");
      out.write("            },\r\n");
      out.write("\t\t\t\r\n");
      out.write("            eventClick : function( events ){\r\n");
      out.write("            },\r\n");
      out.write("            \r\n");
      out.write("            dayClick : function (date, allDay, jsEvent, view){\r\n");
      out.write("            \t$(\".clicking-test\").each(function () {\r\n");
      out.write("        \t\t\tthis.setAttribute(\"class\",this.getAttribute(\"class\").replace(\" clicking-test\", \"\"));\r\n");
      out.write("                });\r\n");
      out.write("            \tvar cla = this.getAttribute(\"class\").replace(\" clicking-test\", \"\");\r\n");
      out.write("            \tcla = cla + \" clicking-test\";\r\n");
      out.write("            \tthis.setAttribute(\"class\", cla);\r\n");
      out.write("            \tvar time1 = view.title + \"/\" + this.innerText;\r\n");
      out.write("            \tvar a = time1.split(\"/\");\r\n");
      out.write("            \tvar aryweek = new Array(\"四\",\"五\",\"六\",\"日\",\"一\",\"二\",\"三\");\r\n");
      out.write("            \tvar gDay = new Date(a[0],a[1],a[2]).getDay();\r\n");
      out.write("            \tweekWrite(aryweek[gDay],Number(this.innerText));\r\n");
      out.write("            \tvar data = ajaxSumbitNoform(\"test/dateString.do\",time1);\r\n");
      out.write("            \tdocument.getElementById(\"dateWeek\").style.display=\"\";\r\n");
      out.write("            \tadddiv(data);\r\n");
      out.write("            },\r\n");
      out.write("            \r\n");
      out.write("            titleFormat: 'yyyy/MM',\r\n");
      out.write("            isRTL: false,\r\n");
      out.write("    \t\tfirstDay: 1,\r\n");
      out.write("    \t\tdayNamesShort: ['日','一','二','三','四','五','六'],\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tbuttonText: {\r\n");
      out.write("    \t\t    prev: \"<div class='circleA'><div class='triangle-left1'></div></div>\",\r\n");
      out.write("    \t\t    next: \"<div class='circleA' style='padding-left:8px;'><div class='triangle-right'></div></div>\",\r\n");
      out.write("    \t\t    //prevYear: \"<span class='fc-text-arrow'>&laquo;上一年</span>\",\r\n");
      out.write("    \t\t    //nextYear: \"<span class='fc-text-arrow'>下一年&raquo;</span>\"\r\n");
      out.write("    \t\t},\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<body bgcolor=\"#F4F9F9\" onload=\"init()\" style=\"overflow-y:auto;\">\r\n");
      out.write("\t<div style=\"width:100%;height:60px;background: #32373C;position:absolute;top:expression(documentElement.scrollTop + 'px');position:fixed;z-index:9999;\">\r\n");
      out.write("\t\t<table style=\"width:100%;white-space: nowrap;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"19%\" style=\"padding-left:13%;\"><a href=\"#\" onclick=\"javascript:top.location.href='homepage.jsp'\"><img src=\"../img/U-Offerlogo.png\" width=\"109px\" height=\"26px\"></a></td>\r\n");
      out.write("\t\t\t\t<td width=\"5%\"/>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t    <button type=\"button\" style=\"height:60px !important;color:#F5F8F9;background-color:#32373C;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu3\" data-toggle=\"dropdown\" class=\"btn dropdown-toggle\" id=\"dropdownMenu3\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\" onclick=\"javascript:top.location.href='finduser.jsp'\">\r\n");
      out.write("\t\t\t\t    \t<font style=\"font-size:14px;\" color=\"#F5F8F9\">候选人</font>\r\n");
      out.write("\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t    <button type=\"button\" style=\"height:60px !important;color:#F5F8F9;background-color:#777777;\"class=\"btn dropdown-toggle\" id=\"dropdownMenu2\" data-toggle=\"dropdown\" onclick=\"javascript:top.location.href='user_view.jsp'\">\r\n");
      out.write("\t\t\t\t    \t<font style=\"font-size:14px;\" color=\"#F5F8F9\">已发邀请</font>\r\n");
      out.write("\t\t\t\t    </button>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t    <td width=\"5%\"/>\r\n");
      out.write("\t\t\t    <td style=\"width:19%;padding-right:10%\">\r\n");
      out.write("\t\t\t\t    <div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" style=\"height:60px !important;color:#FFF;background-color:#32373C;\"\r\n");
      out.write("\t\t\t\t\t\t class=\"btn dropdown-toggle\" id=\"dropdownMenu2\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\"\r\n");
      out.write("\t\t\t\t\t\t onmouseout=\"changeColor2(this)\" ><span id=\"userName\"></span>\r\n");
      out.write("\t\t\t\t\t        <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t\t    <ul class=\"dropdown-menu pull-right\" role=\"menu\" aria-labelledby=\"dropdownMenu2\" style=\"background-color:#32373C;width:150px;\">\r\n");
      out.write("\t\t\t\t\t        <li role=\"presentation\">\r\n");
      out.write("\t\t\t\t\t            <a role=\"menuitem\" tabindex=\"-1\" href=\"#\" onclick=\"javascript:top.location.href='personal_settings_edit.jsp'\" style=\"height:46px;text-align:center;padding-top:10px;\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\"><font color=\"#F5F8F9\">个人设置</font></a>\r\n");
      out.write("\t\t\t\t\t            <a role=\"menuitem\" tabindex=\"-1\" href=\"#\" onclick=\"javascript:top.location.href='firm_resume_add.jsp'\" style=\"height:46px;text-align:center;padding-top:10px;\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\"><font color=\"#F5F8F9\">企业信息</font></a>\r\n");
      out.write("\t\t\t\t\t        </li>\r\n");
      out.write("\t\t\t\t\t    </ul>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <button type=\"button\" style=\"height:60px !important;color:#FFF;background-color:#32373C;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu4\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\" onclick=\"javascript:top.location.href='login.jsp'\">退出\r\n");
      out.write("\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table width=\"100%\" height=\"95%\" style=\"min-width:1000px;background:#F4F9F9;position:fixed;margin-top:55px;overflow-y:auto;\">\r\n");
      out.write("\t\t<tr height=\"30px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"19%\"/>\r\n");
      out.write("\t\t\t<td style=\"min-width:200px;width:13%;\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"usertype\" name=\"usertype\" value=\"'0','1'\"/>\r\n");
      out.write("\t\t\t\t<table width=\"100%\" style=\"background:#FFF\">\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"font-size:14px;color:#4F4F4F;border-bottom:1px #E3E6E6 solid;cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:25%;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" id=\"type1\" onclick=\"selectInterviewType(1)\"><font id=\"type111\" >等待候选人回应</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"font-size:14px;color:#4F4F4F;border-bottom:1px #E3E6E6 solid;cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:25%;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" id=\"type2\" onclick=\"selectInterviewType(2)\"><font id=\"type222\" >待安排面试</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"font-size:14px;color:#4F4F4F;border-bottom:1px #E3E6E6 solid;cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:25%;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" id=\"type3\" onclick=\"selectInterviewType(3)\"><font id=\"type333\" >待反馈结果</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"font-size:14px;color:#4F4F4F;border-bottom:1px #E3E6E6 solid;cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:25%;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" id=\"type4\" onclick=\"selectInterviewType(4)\"><font id=\"type444\" >面试通过</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"font-size:14px;color:#4F4F4F;border-bottom:1px #E3E6E6 solid;cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:25%;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" id=\"type5\" onclick=\"selectInterviewType(5)\"><font id=\"type555\" >归档</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"font-size:14px;background:#00B38A;color:#FFF;border-bottom:1px #E3E6E6 solid;cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:25%;\" id=\"type6\" onclick=\"selectInterviewType(6)\"><font>面试安排表</font></td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"20px\" style=\"border-right:2px #0dad87 solid;\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\" style=\"float:right\" id=\"type11\"></div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\" style=\"float:right\" id=\"type12\"></div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\" style=\"float:right\" id=\"type13\"></div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\" style=\"float:right\" id=\"type14\"></div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\" style=\"float:right\" id=\"type15\"></div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"triangle-left\" style=\"float:right\" id=\"type16\"></div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"textL\" valign=\"top\" width=\"35%\" style=\"min-width:460px;background:#FFF;\">\r\n");
      out.write("\t\t\t\t<div id='calendar' style=\"width:100%;float:top;background:#FFF;\"></div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"200px\">\r\n");
      out.write("\t\t\t\t<div style=\"overflow-y:auto;width:100%;height:100%;border:1px #CCCCCC solid;background:#FFF;\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\" height=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"64px\" style=\"border-bottom:1px #CCCCCC solid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-left:20px;white-space: nowrap;display:none;\" id=\"dateWeek\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font color=\"#00B38A\" id=\"dayNum\" style=\"font-size:20px;\">26</font>th&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font id=\"weekName\" style=\"font-size:14px;\">星期二</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td id=\"interviewContent\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td/>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"260px\"/>\r\n");
      out.write("\t\t<tr height=\"81px\">\r\n");
      out.write("\t\t\t<td class=\"textC\" colspan=\"6\" style=\"background:#32373C;\">\r\n");
      out.write("\t\t\t\t<font color=\"#F5F8F9\" style=\"font-size:14px;white-space: nowrap;\">\r\n");
      out.write("\t\t\t\t\t关于我们&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t使用攻略&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t法律声明&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t关注我们\r\n");
      out.write("\t\t\t\t</font>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
