/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-05-10 13:55:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class email_005fuser_005ffail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr height=\"29px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"33px\"></td>\r\n");
      out.write("\t\t\t<td width=\"119px\"><font style=\"font-size:30px;\" color=\"#4F4F4F\">U -<font color=\"#00B38A\">O</font>ffer</font></td>\r\n");
      out.write("\t\t\t<td width=\"17px\"></td>\r\n");
      out.write("\t\t\t<td><font style=\"font-size:18px;\" color=\"#4F4F4F\">互联网高端招聘网</font></td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"29px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t<div style=\"height:20px;width:540px;background:url('../img/email_title.jpg');border-radius:10px;\"></div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"29px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t<div style=\"width:540px;\">\r\n");
      out.write("\t\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\" >\r\n");
      out.write("\t\t\t\t\t\tDear 李先生，<br/>\r\n");
      out.write("\t\t\t\t\t\t我们已经收到了您的申请，很高兴您选择U-offer<br/>\r\n");
      out.write("\t\t\t\t\t\t为了保证使用体验，我们的顾问会在2个工作日内与你联系沟通，审核结果\r\n");
      out.write("\t\t\t\t\t\t会在2个工作日内通知您。简历的完整度很大程度上决定了您能否通过审核 \r\n");
      out.write("\t\t\t\t\t\t，您的简历完整度为70%，您可以继续完善简历，审核时我们会以您的最新\r\n");
      out.write("\t\t\t\t\t\t简历为准。\r\n");
      out.write("\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"28px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t<font style=\"font-size:18px;\" color=\"#4F4F4F\" >\r\n");
      out.write("\t\t\t\t\t来看看申请通过后会发生什么\r\n");
      out.write("\t\t\t\t</font>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"13px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\" >\r\n");
      out.write("\t\t\t\t\t您的简历向签约企业展示2周 <br/>\r\n");
      out.write("\t\t\t\t\t企业向您发出面试邀请，声明职位及薪资  <br/>\r\n");
      out.write("\t\t\t\t\t选择您满意的参加面试，挑选满意的offer入职\r\n");
      out.write("\t\t\t\t</font>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"60px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"121px\" rowspan=\"7\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:121px;height:121px;border:1px #CCCCCC solid;border-radius:20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-left:30px;margin-top:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../img/kefu.png\" width=\"60px\" height=\"90px\" style=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"49px\" rowspan=\"7\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><font style=\"font-size:16px;\" color=\"#4F4F4F\">希望获得帮助，联系顾问</font></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t\t\t\t我是张丽，您的职业顾问。\r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t\t\t\t期待着与您交流工作、求职中的想法。\r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t\t\t\t电话：\r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t\t\t\t微信：\r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t\t\t\tQQ：1611972891 \r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t\t\t\t邮箱：\r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"40px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t<div style=\"height:20px;width:540px;background:url('../img/email_title.jpg');border-radius:10px;\"></div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"59px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\" style=\"text-align:center;\">\r\n");
      out.write("\t\t\t\t<font style=\"font-size:14px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t此邮件由U-offer发送，\r\n");
      out.write("\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t<font style=\"font-size:14px;\" color=\"#00B389\">\r\n");
      out.write("\t\t\t\t\t\t取消推送邮件订阅？\r\n");
      out.write("\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"69px\"/>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
