/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-05-11 04:02:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class email_005ftuijian_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr height=\"29px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"33px\"></td>\r\n");
      out.write("\t\t\t<td width=\"119px\"><font style=\"font-size:30px;\" color=\"#4F4F4F\">U -<font color=\"#00B38A\">O</font>ffer</font></td>\r\n");
      out.write("\t\t\t<td width=\"17px\"></td>\r\n");
      out.write("\t\t\t<td><font style=\"font-size:18px;\" color=\"#4F4F4F\">互联网高端招聘网</font></td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"29px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t<div style=\"height:20px;width:540px;background:url('../img/email_title.jpg');border-radius:10px;\"></div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"29px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t亲爱的廖珈浚：<br/>\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t根据您填写的招聘需求问卷，u<font color=\"#00B389\">o</font>ffer为您推荐以下高端候选人：<br/>\r\n");
      out.write("\t\t\t\t\t如有适合的请尽快发送面试邀请，以免错失优质候选人。<br/>\r\n");
      out.write("\t\t\t\t</font>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"15px\"><td colspan=\"5\" style=\"border-bottom:1px #CCCCCC solid;\"></td></tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 11111111111111111111111111111111111111111111111111111111111 -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\" style=\"border-bottom:1px #CCCCCC solid;padding-top:39px;padding-bottom:28px;\">\r\n");
      out.write("\t\t\t\t<table width=\"541px\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"5\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:60px;heihgt:60px;border-radius:50%; overflow:hidden;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../img/changjinglu.jpg\" width=\"60px\" height=\"60px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"29px\" rowspan=\"5\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><font style=\"color:#4F4F4F;font-size:16px;\">广州市 /本科/4年java开发经验/目前年薪为 ¥ 37.5万</font></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"18px\"></tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"color:#00B389;font-size:16px;\">期望工作:</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"11px\"></tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"308px\"><font style=\"color:#4F4F4F;font-size:16px;\">Android工程师 ,Ios 工程师 </font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td rowspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a style=\"border-radius:20px;line-height:37px;text-align:center;float:right;width:101px;height:37px;font-size:16px;background:#FFF;border:1px #00B389 solid;color:#00B389;display:block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t邀请\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><font style=\"color:#4F4F4F;font-size:16px;\">期望年薪 ¥ 45万/广州，深圳</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><font style=\"color:#4F4F4F;font-size:16px;\">期望在C轮以上，已上市或不需要融资工作。 期望在C轮以上，已上市或不需要融资工作。 </font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 222222222222222222222222222 -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\" style=\"border-bottom:1px #CCCCCC solid;padding-top:39px;padding-bottom:28px;\">\r\n");
      out.write("\t\t\t\t<table width=\"541px\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"5\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:60px;heihgt:60px;border-radius:50%; overflow:hidden;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../img/changjinglu.jpg\" width=\"60px\" height=\"60px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"29px\" rowspan=\"5\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><font style=\"color:#4F4F4F;font-size:16px;\">广州市 /本科/4年java开发经验/目前年薪为 ¥ 37.5万</font></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"18px\"></tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"color:#00B389;font-size:16px;\">期望工作:</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"11px\"></tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"308px\"><font style=\"color:#4F4F4F;font-size:16px;\">Android工程师 ,Ios 工程师 </font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td rowspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a style=\"border-radius:20px;line-height:37px;text-align:center;float:right;width:101px;height:37px;font-size:16px;background:#FFF;border:1px #00B389 solid;color:#00B389;display:block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t邀请\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><font style=\"color:#4F4F4F;font-size:16px;\">期望年薪 ¥ 45万/广州，深圳</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><font style=\"color:#4F4F4F;font-size:16px;\">期望在C轮以上，已上市或不需要融资工作。 期望在C轮以上，已上市或不需要融资工作。 </font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr height=\"45px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"121px\" rowspan=\"5\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:121px;height:121px;border:1px #CCCCCC solid;border-radius:20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-left:30px;margin-top:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../img/kefu.png\" width=\"60px\" height=\"90px\" style=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"49px\" rowspan=\"5\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"28px\" valign=\"top\"><font style=\"font-size:16px;\" color=\"#4F4F4F\">我是蓝天，你的招聘助理</font></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t\t\t\t联系电话：13250325307\r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t\t\t\t微信号：13250325307\r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t\t\t\tQQ：1611972891 \r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"font-size:16px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t\t\t\t邮箱：lantian@uoffer.com\r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"40px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t<div style=\"height:20px;width:540px;background:url('../img/email_title.jpg');border-radius:10px;\"></div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"59px\"/>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\" style=\"text-align:center;\">\r\n");
      out.write("\t\t\t\t<font style=\"font-size:14px;\" color=\"#4F4F4F\">\r\n");
      out.write("\t\t\t\t\t如果您不再希望接收该提醒邮件,您可以点击 \r\n");
      out.write("\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t<font style=\"font-size:14px;\" color=\"#00B389\">\r\n");
      out.write("\t\t\t\t\t\t一键退订\r\n");
      out.write("\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"69px\"/>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
