/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-03-31 10:48:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class fileUpload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1490952086044L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>My JSP 'index.jsp' starting page</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../css/base.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../skins/all.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../img/title.ico\" type=\"image/x-icon\"/>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxfileupload.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxSubmit.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"../js/Carousel.js\"></script>\r\n");
      out.write("<script src=\"../js/jquery.icheck.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/locales/bootstrap-datetimepicker.zh-CN.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction upload() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"register/firm.do\", // 自行按需配置好完整的url，包括ip和端口号  \r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdatatype : \"text\",\r\n");
      out.write("\t\t\tdata : JSON.stringify($(\"#form1\").serializeObject()),\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//头部\r\n");
      out.write("\tfunction changeColor1(der){\r\n");
      out.write("\t\tder.style.background=\"#CCCCCC\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor2(der){\r\n");
      out.write("\t\tder.style.background=\"#32373C\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function test(){\r\n");
      out.write("\tvar url = \"user/filefilefile.do\";\r\n");
      out.write("\tvar files = ['file1','file2','file3'];\r\n");
      out.write("\tvar formId = \"loginForm\";\r\n");
      out.write("\tfileUpload(url,files);\r\n");
      out.write("}\r\n");
      out.write("\tfunction fileUpload(urllink, files) {  \r\n");
      out.write("\t\tvar link = \"/hibernateMvc/\" + urllink;\r\n");
      out.write("\t    var files = ['file1','file2','file3'];  //将上传三个文件 ID 分别为file2,file2,file3  \r\n");
      out.write("\t    $.ajaxFileUpload( {  \r\n");
      out.write("\t        url : link,     //用于文件上传的服务器端请求地址    \r\n");
      out.write("\t        secureuri : false,            //一般设置为false    \r\n");
      out.write("\t        fileElementId : files,        //文件上传的id属性  <input type=\"file\" id=\"file\" name=\"file\" />    \r\n");
      out.write("\t        dataType : 'json',            //返回值类型 一般设置为json    \r\n");
      out.write("\t        success : function(data, status) {  \r\n");
      out.write("\t        \t/*var fileNames = data.fileFileName; //返回的文件名   \r\n");
      out.write("\t            var filePaths = data.filePath;     //返回的文件地址   \r\n");
      out.write("\t            for(var i=0;i<data.fileFileName.length;i++){  \r\n");
      out.write("\t                //将上传后的文件 添加到页面中 以进行下载  \r\n");
      out.write("\t                $(\"#down\").after(\"<tr><td height='25'>\"+fileNames[i]+  \r\n");
      out.write("\t                        \"</td><td><a href='downloadFile?downloadFilePath=\"+filePaths[i]+\"'>下载</a></td></tr>\")  \r\n");
      out.write("\t            } */\r\n");
      out.write("\t        }  \r\n");
      out.write("\t    })  \r\n");
      out.write("\t}\r\n");
      out.write("\t/* var content = document.getElementById(\"textTest\").value;\r\n");
      out.write("\tvar userAgent = navigator.userAgent;\r\n");
      out.write("\tvar isOpera = userAgent.indexOf(\"Opera\") > -1;\r\n");
      out.write("\tvar browser;\r\n");
      out.write("\tif(isOpera){\r\n");
      out.write("\t\tbrowser=\"Opera\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(userAgent.indexOf(\"Firefox\") > -1){\r\n");
      out.write("\t\tbrowser=\"FF\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(userAgent.indexOf(\"Chrome\") > -1){\r\n");
      out.write("\t\tbrowser=\"Chrome\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(userAgent.indexOf(\"Safari\") > -1){\r\n");
      out.write("\t\tbrowser=\"Safari\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(userAgent.indexOf(\"compatible\") > -1 && userAgent.indexOf(\"MSIE\") > -1 && !isOpera){\r\n");
      out.write("\t\tbrowser=\"IE\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(browser == 'FF'){\r\n");
      out.write("\t\t//火狐\r\n");
      out.write("\t\tcontent = content.replace(\"/(\\r)*\\n/g\",\"<br/>\");\r\n");
      out.write("\t\tcontent = content.replace(\"/\\s/g\",\"&nbsp;\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tcontent = content.replace(\"\\n\",\"<br/>\");\r\n");
      out.write("\t\tcontent = content.replace(\" \",\"&nbsp;\");\r\n");
      out.write("\t}\r\n");
      out.write("\talert(content);\r\n");
      out.write("\tvar url = \"test/testString.do\";\r\n");
      out.write("\tvar formId = \"caozuoForm\";\r\n");
      out.write("\tvar data = ajaxSumbitNoform(url, content); */\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<body bgcolor=\"#F4F9F9\">\r\n");
      out.write("\t<form id=\"loginForm\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<input type=\"file\" id=\"file1\" name=\"file\"/>\r\n");
      out.write("\t\t<input type=\"file\" id=\"file2\" name=\"filea\"/>\r\n");
      out.write("\t\t<input type=\"file\" id=\"file3\" name=\"file\"/>\r\n");
      out.write("\t\t<input type=\"file\" id=\"file4\" name=\"file\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"asd\" value=\"123\"/>\r\n");
      out.write("\t\t<input type=\"button\" onclick=\"test()\" value=\"1111111\"/>\r\n");
      out.write("\t\t<textarea id=\"textTest\"></textarea>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
