/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-05-15 06:27:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class maininterview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1494475596723L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>My JSP 'index.jsp' starting page</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../css/base.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../skins/all.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- <link href=\"../css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\" /> -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../img/title.ico\" type=\"image/x-icon\"/>\r\n");
      out.write("<style>\r\n");
      out.write("\t.btn.dropdown-toggle{\r\n");
      out.write("\t\tbackground:#CCCCCC;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxfileupload.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxSubmit.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- <script src=\"../js/Carousel.js\"></script> -->\r\n");
      out.write("<script src=\"../js/jquery.icheck.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.min.js\"></script>\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"../js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/locales/bootstrap-datetimepicker.zh-CN.js\"></script> -->\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction upload() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"register/firm.do\", // 自行按需配置好完整的url，包括ip和端口号  \r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdatatype : \"text\",\r\n");
      out.write("\t\t\tdata : JSON.stringify($(\"#form1\").serializeObject()),\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//头部\r\n");
      out.write("\tfunction changeColor1(der){\r\n");
      out.write("\t\tder.style.background=\"#777777\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor2(der){\r\n");
      out.write("\t\tder.style.background=\"#32373C\";\r\n");
      out.write("\t}\r\n");
      out.write("\tjQuery(function($){\r\n");
      out.write("\t\t$(\".dropdown .form-control\").click(function(){\r\n");
      out.write("\t\t\tif(this.parentNode.getElementsByTagName(\"button\") == undefined){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tthis.parentNode.getElementsByTagName(\"button\")[0].click();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<style>\r\n");
      out.write(".greenTd{\r\n");
      out.write("\tbackground:#00B38A !important;\r\n");
      out.write("\tcolor:#FFF !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tvar type1, type2, type3, type4, type5, type6;\r\n");
      out.write("\tfunction init() {\r\n");
      out.write("\t\tvar url = \"firm/interviewPage1.do\";\r\n");
      out.write("\t\tvar formId = \"testForm\";\r\n");
      out.write("\t\tvar data = ajaxSumbit(url, formId);\r\n");
      out.write("\t\taddtags(\"type1\",\"新的面试邀请(\"+data.interview1+\")\");\r\n");
      out.write("\t\taddtags(\"type2\",\"待沟通(\"+data.interview2+\")\");\r\n");
      out.write("\t\taddtags(\"type3\",\"待安排面试(\"+data.interview3+\")\");\r\n");
      out.write("\t\taddtags(\"type4\",\"已安排面试(\"+data.interview4+\")\");\r\n");
      out.write("\t\taddtags(\"type5\",\"面试结果(\"+data.interview5+\")\");//4通过,5没通过\r\n");
      out.write("\t\taddtags(\"type6\",\"已拒绝面试邀请(\"+data.interview6+\")\");\r\n");
      out.write("\t\tdocument.getElementById(\"type1\").setAttribute(\"class\",\"greenTd\");\r\n");
      out.write("\t\ttype1 = data.interview1;\r\n");
      out.write("\t\ttype2 = data.interview2;\r\n");
      out.write("\t\ttype3 = data.interview3;\r\n");
      out.write("\t\ttype4 = data.interview4;\r\n");
      out.write("\t\ttype5 = data.interview5;\r\n");
      out.write("\t\ttype6 = data.interview6;\r\n");
      out.write("\t\tif (data.interview1 > 0) {\r\n");
      out.write("\t\t\tgoSearch();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\tnoValue();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//头部\r\n");
      out.write("\tfunction changeColor1(der){\r\n");
      out.write("\t\tder.style.background=\"#777777\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor2(der){\r\n");
      out.write("\t\tder.style.background=\"#32373C\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor3(der){\r\n");
      out.write("\t\tder.style.background=\"#00B38A\";\r\n");
      out.write("\t\tder.style.color=\"#FFF\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor4(der){\r\n");
      out.write("\t\tder.style.background=\"#FFF\";\r\n");
      out.write("\t\tder.style.color=\"#666666\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction jobId(job){\r\n");
      out.write("\t\tif(job.getAttribute('class') == \"icheckbox_square-green checked\"){\r\n");
      out.write("\t\t\tjob.setAttribute(\"class\",\"icheckbox_square-green hover\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(job.getAttribute('class') == \"icheckbox_square-green hover\"){\r\n");
      out.write("\t\t\tjob.setAttribute(\"class\",\"icheckbox_square-green checked\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction selectInterviewType(seqno){\r\n");
      out.write("\t\twindow.iframe2.location.href=\"e.html\";\r\n");
      out.write("\t\t$(\".greenTd\").each(function () {\r\n");
      out.write("\t\t\tthis.setAttribute(\"class\",\"\");\r\n");
      out.write("        });\r\n");
      out.write("\t\tvar tdId = \"type\" + seqno;\r\n");
      out.write("\t\tdocument.getElementById(tdId).setAttribute(\"class\",\"greenTd\");\r\n");
      out.write("\t\t$(\".triangle-left\").each(function () {\r\n");
      out.write("\t\t\tthis.setAttribute(\"class\",\"\");\r\n");
      out.write("        });\r\n");
      out.write("\t\tif(seqno == 1){\r\n");
      out.write("\t\t\tdocument.getElementById(\"type11\").setAttribute(\"class\",\"triangle-left\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"interviewtype\").value = \"'0','1'\";//0,1\r\n");
      out.write("\t\t\tif (type1 > 0) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewnone\").style.display=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewntwo\").style.display=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewtd\").style.display=\"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(seqno == 2){\r\n");
      out.write("\t\t\tdocument.getElementById(\"type12\").setAttribute(\"class\",\"triangle-left\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"interviewtype\").value = seqno - 1;//1\r\n");
      out.write("\t\t\tif (type2 > 0) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewnone\").style.display=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewntwo\").style.display=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewtd\").style.display=\"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(seqno == 3){\r\n");
      out.write("\t\t\tdocument.getElementById(\"type13\").setAttribute(\"class\",\"triangle-left\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"interviewtype\").value = seqno - 1;//2\r\n");
      out.write("\t\t\tif (type3 > 0) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewnone\").style.display=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewntwo\").style.display=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewtd\").style.display=\"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(seqno == 4){\r\n");
      out.write("\t\t\tdocument.getElementById(\"type14\").setAttribute(\"class\",\"triangle-left\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"interviewtype\").value = seqno - 1;//3\r\n");
      out.write("\t\t\tif (type4 > 0) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewnone\").style.display=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewntwo\").style.display=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewtd\").style.display=\"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(seqno == 5){\r\n");
      out.write("\t\t\tdocument.getElementById(\"type15\").setAttribute(\"class\",\"triangle-left\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"interviewtype\").value = \"'4','5','7'\";//4,5\r\n");
      out.write("\t\t\tif (type5 > 0) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewnone\").style.display=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewntwo\").style.display=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewtd\").style.display=\"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(seqno == 6){\r\n");
      out.write("\t\t\tdocument.getElementById(\"type16\").setAttribute(\"class\",\"triangle-left\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"interviewtype\").value = \"'6','8'\";//6,8\r\n");
      out.write("\t\t\tif (type6 > 0) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewnone\").style.display=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewntwo\").style.display=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"viewtd\").style.display=\"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tgoSearch();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction addtags(typeId,typemsg){\r\n");
      out.write("\t\tdocument.getElementById(typeId).innerHTML=\"<font style='font-size:14px;'>\"+typemsg+\"</font>\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction goSearch(){\r\n");
      out.write("\t\twindow.iframe1.location.href=\"maininterview_object.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction noValue(){\r\n");
      out.write("\t\tdocument.getElementById(\"viewtd\").style.display=\"\";\r\n");
      out.write("\t\tdocument.getElementById(\"viewnone\").style.display=\"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"viewntwo\").style.display=\"none\";\r\n");
      out.write("\t\twindow.noValueiframe.location.href=\"noValue.html\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body bgcolor=\"#F5F8F9\" onload=\"init()\">\r\n");
      out.write("\t<form id=\"testForm\"></form>\r\n");
      out.write("\t<input type=\"hidden\" id=\"inviteId\" name=\"inviteId\" />\r\n");
      out.write("\t<div style=\"width:100%;height:60px;min-width:1000px;background: #32373C;position:absolute;top:expression(documentElement.scrollTop + 'px');position:fixed;z-index:9999;\">\r\n");
      out.write("\t\t<table style=\"width:100%;white-space: nowrap;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"19%\" style=\"padding-left:14%;\"><a href=\"#\" onclick=\"javascript:top.location.href='homepage.jsp'\"><img src=\"../img/U-Offerlogo.png\" width=\"109px\" height=\"26px\"></a></td>\r\n");
      out.write("\t\t\t\t<td width=\"5%\"/>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t    <button type=\"button\" style=\"font-size:14px;height:60px !important;color:#F5F8F9;background-color:#777777;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu3\" data-toggle=\"dropdown\" class=\"btn dropdown-toggle\" id=\"dropdownMenu3\" data-toggle=\"dropdown\" onclick=\"javascript:top.location.href='interview.jsp'\">\r\n");
      out.write("\t\t\t\t    \t<font>面试邀请</font>\r\n");
      out.write("\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t    <button type=\"button\" style=\"font-size:14px;height:60px !important;color:#F5F8F9;background-color:#32373C;\"class=\"btn dropdown-toggle\" id=\"dropdownMenu2\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\" onclick=\"javascript:top.location.href='resume_edit.jsp'\">\r\n");
      out.write("\t\t\t\t    \t<font>我的简历</font>\r\n");
      out.write("\t\t\t\t    </button>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t    <td width=\"5%\"/>\r\n");
      out.write("\t\t\t    <td class=\"textR\" style=\"width:19%;padding-right:10%\">\r\n");
      out.write("\t\t\t\t    <button type=\"button\" style=\"font-size:14px;height:60px !important;color:#F5F8F9;background-color:#32373C;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu1\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\" onclick=\"javascript:top.location.href='personal_settings.jsp'\">个人设置\r\n");
      out.write("\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t    <button type=\"button\" style=\"font-size:14px;height:60px !important;color:#F5F8F9;background-color:#32373C;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu4\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\" onclick=\"javascript:top.location.href='login.jsp'\">退出\r\n");
      out.write("\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- <div style=\"width:100%;height:75px;\"></div> -->\r\n");
      out.write("\t<table width=\"100%\" height=\"100%\" style=\"min-width:1000px;position:fixed;margin-top:80px;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"19%\" rowspan=\"10\"/>\r\n");
      out.write("\t\t\t<td rowspan=\"10\" valign=\"top\" style=\"min-width:200px;width:13%;\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"interviewtype\" name=\"interviewtype\" value=\"1\"/>\r\n");
      out.write("\t\t\t\t<table width=\"100%\" style=\"background:#FFF\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textL\" style=\"border-bottom:1px #E3E6E6 solid;cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:25%;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" id=\"type1\" onclick=\"selectInterviewType(1)\">\r\n");
      out.write("\t\t\t\t\t\t\t<font>新的面试邀请</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"border-bottom:1px #E3E6E6 solid;cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:25%;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" id=\"type2\" onclick=\"selectInterviewType(2)\"><font>待沟通</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"border-bottom:1px #E3E6E6 solid;cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:25%;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" id=\"type3\" onclick=\"selectInterviewType(3)\"><font>待安排面试</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"border-bottom:1px #E3E6E6 solid;cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:25%;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" id=\"type4\" onclick=\"selectInterviewType(4)\"><font>已安排面试</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"border-bottom:1px #E3E6E6 solid;cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:25%;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" id=\"type5\" onclick=\"selectInterviewType(5)\"><font>面试结果</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"border-bottom:1px #E3E6E6 solid;cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:25%;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" id=\"type6\" onclick=\"selectInterviewType(6)\"><font>已拒绝面试邀请</font></td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"30px\" style=\"border-right:2px #0dad87 solid;\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"triangle-left\" style=\"float:right\" id=\"type11\"></div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\" style=\"float:right\" id=\"type12\"></div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\" style=\"float:right\" id=\"type13\"></div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\" style=\"float:right\" id=\"type14\"></div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\" style=\"float:right\" id=\"type15\"></div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\" style=\"float:right\" id=\"type16\"></div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"textL\" width=\"13%\" valign=\"top\" height=\"84%\" style=\"min-width:180px;display:none;\" id=\"viewnone\">\r\n");
      out.write("\t\t\t\t<iframe height=\"100%\" width=\"100%\" scrolling=\"auto\" frameborder=\"0\" marginheight=\"0px\" marginwidth=\"0px\" style=\"background:#FFF;\" id=\"iframe1\" name=\"iframe1\"></iframe>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"textL\" valign=\"top\" height=\"84%\" style=\"min-width:460px;min-height:84%;display:none;\" id=\"viewntwo\">\r\n");
      out.write("\t\t\t\t<iframe height=\"100%\" width=\"100%\" scrolling=\"auto\" frameborder=\"0\" marginheight=\"0px\" marginwidth=\"0px\" style=\"background:#FFF;border:1px #CCCCCC solid;\" id=\"iframe2\" name=\"iframe2\"></iframe>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"textL\" valign=\"top\" height=\"84%\" id=\"viewtd\" style=\"min-height:84%;display:none;\">\r\n");
      out.write("\t\t\t\t<iframe height=\"100%\" width=\"100%\" scrolling=\"auto\" frameborder=\"0\" marginheight=\"0px\" marginwidth=\"0px\" style=\"background:#FFF;border:1px #CCCCCC solid;\"  id=\"noValueiframe\" name=\"noValueiframe\"></iframe>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"19%\"/>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
