/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-05-15 07:03:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class mainteam_005fmember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1494475596723L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>My JSP 'index.jsp' starting page</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../css/base.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../skins/all.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- <link href=\"../css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\" /> -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../img/title.ico\" type=\"image/x-icon\"/>\r\n");
      out.write("<style>\r\n");
      out.write("\t.btn.dropdown-toggle{\r\n");
      out.write("\t\tbackground:#CCCCCC;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxfileupload.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxSubmit.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- <script src=\"../js/Carousel.js\"></script> -->\r\n");
      out.write("<script src=\"../js/jquery.icheck.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.min.js\"></script>\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"../js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/locales/bootstrap-datetimepicker.zh-CN.js\"></script> -->\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction upload() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"register/firm.do\", // 自行按需配置好完整的url，包括ip和端口号  \r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdatatype : \"text\",\r\n");
      out.write("\t\t\tdata : JSON.stringify($(\"#form1\").serializeObject()),\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//头部\r\n");
      out.write("\tfunction changeColor1(der){\r\n");
      out.write("\t\tder.style.background=\"#777777\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor2(der){\r\n");
      out.write("\t\tder.style.background=\"#32373C\";\r\n");
      out.write("\t}\r\n");
      out.write("\tjQuery(function($){\r\n");
      out.write("\t\t$(\".dropdown .form-control\").click(function(){\r\n");
      out.write("\t\t\tif(this.parentNode.getElementsByTagName(\"button\") == undefined){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tthis.parentNode.getElementsByTagName(\"button\")[0].click();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<style>\r\n");
      out.write("\t.gray{\r\n");
      out.write("\t\tborder:1px #CCCCCC solid;\r\n");
      out.write("\t\theight:47px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tvar isNowAdmin;\r\n");
      out.write("\tfunction changeColor1(der){\r\n");
      out.write("\t\tder.style.background=\"#777777\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor2(der){\r\n");
      out.write("\t\tder.style.background=\"#32373C\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor3(der){\r\n");
      out.write("\t\tder.style.background=\"#00B38A\";\r\n");
      out.write("\t\tder.style.color=\"#FFF\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor4(der){\r\n");
      out.write("\t\tder.style.background=\"#FFF\";\r\n");
      out.write("\t\tder.style.color=\"#4F4F4F\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction booleanInfot(url){\r\n");
      out.write("\t\ttop.location.href=url;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction sendemil(){\r\n");
      out.write("\t\tvar url = \"user/teammemberSandEmail.do\";\r\n");
      out.write("\t\tvar data = ajaxSumbitNoform(url, document.getElementById('tongshiEmail').value);\r\n");
      out.write("\t\tif(data == \"success\"){\r\n");
      out.write("\t\t\t\talert(\"修改成功\");\r\n");
      out.write("\t\t\tinit();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"保存出错！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction init(){\r\n");
      out.write("\t\tgoSearch();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction goSearch(){\r\n");
      out.write("\t\tvar url = \"user/getteammenber.do\";\r\n");
      out.write("\t\tvar formId = \"caozuoForm\";\r\n");
      out.write("\t\tvar data = ajaxSumbit(url, formId);\r\n");
      out.write("\t\taddUserName(data.userName);\r\n");
      out.write("\t\taddIsAdmin(data.isAdmin);\r\n");
      out.write("\t\taddmessage(data.offerUsers1);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction addUserName(items){\r\n");
      out.write("\t\tfor(var i in items){\r\n");
      out.write("\t\t\tdocument.getElementById('userName').innerText = items[i].userName;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction addIsAdmin(items){\r\n");
      out.write("\t\tfor(var i in items){\r\n");
      out.write("\t\t\tdocument.getElementById('isAdmin').value = items[i].isAdmin;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tisNowAdmin = document.getElementById('isAdmin').value;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction addmessage(items){\r\n");
      out.write("\t\tvar isAdmin, teamPeopleStatus;\r\n");
      out.write("\t\tvar me = \"<tr height='40px'>\"+\r\n");
      out.write("\t\t\"<td colspan='6' valign='top'>团队成员</td>\"+\r\n");
      out.write("\t\t\t\"</tr>\"+\r\n");
      out.write("\t\t\t\t\"<tr>\"+\r\n");
      out.write("\t\t\t\t\t\"<td class='gray textC' style='background:#E2E2E2;'>姓名</td>\"+\r\n");
      out.write("\t\t\t\t\t\"<td class='gray textC' style='background:#E2E2E2;'>职位</td>\"+\r\n");
      out.write("\t\t\t\t\t\"<td class='gray textC' style='background:#E2E2E2;'>邮箱</td>\"+\r\n");
      out.write("\t\t\t\t\t\"<td class='gray textC' style='background:#E2E2E2;'>身份</td>\"+\r\n");
      out.write("\t\t\t\t\t\"<td class='gray textC' style='background:#E2E2E2;'>状态</td>\"+\r\n");
      out.write("\t\t\t\t\t\"<td class='gray textC' style='background:#E2E2E2;'>操作</td>\"+\r\n");
      out.write("\t\t\t\t\"</tr>\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tfor(var i in items){\r\n");
      out.write("\t\t\t\tisAdmin = items[i].isAdmin;\r\n");
      out.write("\t\t\t\tteamPeopleStatus = items[i].teamPeopleStatus;\r\n");
      out.write("\t\t\t\tme = me + \"<tr>\" +\r\n");
      out.write("\t\t\t\t\t\"<td class='gray textC'>\"+items[i].name+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\"<td class='gray textC'>\"+items[i].job+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\"<td class='gray textC'>\"+items[i].addree+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\"<td class='gray textC'>\"+items[i].shenfen+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\"<td class='gray textC'>\"+items[i].status+\"</td>\";\r\n");
      out.write("\t\t\t\tif (isNowAdmin == 1) {\r\n");
      out.write("\t\t\t\t\tif (isAdmin != 1) {\r\n");
      out.write("\t\t\t\t\t\tme += \"<td class='gray textC'>\";\r\n");
      out.write("\t\t\t\t\t\tif (teamPeopleStatus == 4) {\r\n");
      out.write("\t\t\t\t\t\t\tme += \"<a href='#' color='00B38A' id='\"+items[i].id+\"' onclick='goChangeStatus(9,\"+items[i].id+\")'>禁用</a>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse if (teamPeopleStatus == 9){\r\n");
      out.write("\t\t\t\t\t\t\tme += \"<a href='#' color='00B38A' id='\"+items[i].id+\"' onclick='goChangeStatus(4,\"+items[i].id+\")'>启用</a>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tme += \"&nbsp;<a href='#' id='\"+items[i].id+\"' onclick='goChangeAdmin(\"+items[i].id+\")'>转移管理员</a></td>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\tme += \"<td class='gray textC'></td>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\tme += \"<td class='gray textC'></td>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tme += \"</tr>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tdocument.getElementById(\"message\").innerHTML= me;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goChangeAdmin( id) {\r\n");
      out.write("\t\tdocument.getElementById('teamPeopleId').value = id;\r\n");
      out.write("\t\tif (confirm(\"确定要转移管理员身份吗？请慎重考虑\")) {\r\n");
      out.write("\t\t\tvar url = \"firm/changeTeamAdmin.do?\";\r\n");
      out.write("\t\t\tvar formId = \"caozuoForm\";\r\n");
      out.write("\t\t\tvar data = ajaxSumbit(url, formId);\r\n");
      out.write("\t\t\tif (data == 'success'){\r\n");
      out.write("\t\t\t\talert(\"已转移管理员！\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (data == 'error') {\r\n");
      out.write("\t\t\t\talert(\"操作错误\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\talert(data);\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tgoSearch();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goChangeStatus(status, id) {\r\n");
      out.write("\t\tdocument.getElementById('teamPeopleStatus').value = status;\r\n");
      out.write("\t\tdocument.getElementById('teamPeopleId').value = id;\r\n");
      out.write("\t\tvar url = \"firm/changeTeamPeopleStatus.do?\";\r\n");
      out.write("\t\tvar formId = \"caozuoForm\";\r\n");
      out.write("\t\tvar data = ajaxSumbit(url, formId);\r\n");
      out.write("\t\tif (data == 'success'){\r\n");
      out.write("\t\t\tif (status == '9') {\r\n");
      out.write("\t\t\t\talert(\"已成功禁用！\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\talert(\"已成功启用！\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if (data == 'error') {\r\n");
      out.write("\t\t\talert(\"操作错误\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tgoSearch();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body bgcolor=\"#F4F9F9\" onload=\"init()\">\r\n");
      out.write("\t<form id=\"caozuoForm\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"teamPeopleStatus\" name=\"teamPeopleStatus\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"teamPeopleId\" name=\"teamPeopleId\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"isAdmin\" name=\"isAdmin\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div style=\"width:100%;height:60px;background: #32373C;position:absolute;top:expression(documentElement.scrollTop + 'px');position:fixed;z-index:9999;\">\r\n");
      out.write("\t\t<table style=\"width:100%;white-space: nowrap;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"19%\" style=\"padding-left:13%;\"><a href=\"#\" onclick=\"javascript:top.location.href='homepage.jsp'\"><img src=\"../img/U-Offerlogo.png\" width=\"109px\" height=\"26px\"></a></td>\r\n");
      out.write("\t\t\t\t<td width=\"5%\"/>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t    <button type=\"button\" style=\"height:60px !important;color:#F5F8F9;background-color:#32373C;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu3\" data-toggle=\"dropdown\" class=\"btn dropdown-toggle\" id=\"dropdownMenu3\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\" onclick=\"javascript:top.location.href='finduser.jsp'\">\r\n");
      out.write("\t\t\t\t    \t<font style=\"font-size:14px;\" color=\"#F5F8F9\">候选人</font>\r\n");
      out.write("\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t    <button type=\"button\" style=\"height:60px !important;color:#F5F8F9;background-color:#32373C;\"class=\"btn dropdown-toggle\" id=\"dropdownMenu2\" data-toggle=\"dropdown\" onclick=\"javascript:top.location.href='user_view.jsp'\">\r\n");
      out.write("\t\t\t\t    \t<font style=\"font-size:14px;\" color=\"#F5F8F9\">已发邀请</font>\r\n");
      out.write("\t\t\t\t    </button>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t    <td width=\"5%\"/>\r\n");
      out.write("\t\t\t    <td style=\"width:19%;padding-right:10%\">\r\n");
      out.write("\t\t\t\t    <div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" style=\"height:60px !important;color:#FFF;background-color:#32373C;\"\r\n");
      out.write("\t\t\t\t\t\t class=\"btn dropdown-toggle\" id=\"dropdownMenu2\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\"\r\n");
      out.write("\t\t\t\t\t\t onmouseout=\"changeColor2(this)\" ><span id=\"userName\"></span>\r\n");
      out.write("\t\t\t\t\t        <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t\t    <ul class=\"dropdown-menu pull-right\" role=\"menu\" aria-labelledby=\"dropdownMenu2\" style=\"background-color:#32373C;width:150px;\">\r\n");
      out.write("\t\t\t\t\t        <li role=\"presentation\">\r\n");
      out.write("\t\t\t\t\t            <a role=\"menuitem\" tabindex=\"-1\" href=\"#\" onclick=\"javascript:top.location.href='personal_settings_edit.jsp'\" style=\"height:46px;text-align:center;padding-top:10px;\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\"><font color=\"#F5F8F9\">个人设置</font></a>\r\n");
      out.write("\t\t\t\t\t            <a role=\"menuitem\" tabindex=\"-1\" href=\"#\" onclick=\"javascript:top.location.href='firm_resume_add.jsp'\" style=\"height:46px;text-align:center;padding-top:10px;\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\"><font color=\"#F5F8F9\">企业信息</font></a>\r\n");
      out.write("\t\t\t\t\t        </li>\r\n");
      out.write("\t\t\t\t\t    </ul>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <button type=\"button\" style=\"height:60px !important;color:#FFF;background-color:#32373C;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu4\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\" onclick=\"javascript:top.location.href='login.jsp'\">退出\r\n");
      out.write("\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<table width=\"100%\" style=\"min-width:1000px;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"19%\" rowspan=\"10\"/>\r\n");
      out.write("\t\t\t<td rowspan=\"2\" width=\"13%\" valign=\"top\" style=\"min-width:180px;\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\" style=\"background:#FFF\">\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textC\" style=\"cursor:pointer;padding-top:15px;padding-bottom:15px;border-bottom:1px #CCCCCC solid;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" onclick=\"javascript:top.location.href='personal_settings_edit.jsp'\"><font style='font-size:14px;'>账号信息</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textC\" style=\"background:#00B38A;color:#FFF;cursor:pointer;padding-top:15px;padding-bottom:15px;border-bottom:1px #CCCCCC solid;\" onclick=\"javascript:top.location.href='team_member.jsp'\"><font style='font-size:14px;'>团队成员</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textC\" style=\"cursor:pointer;padding-top:15px;padding-bottom:15px;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\" onclick=\"javascript:top.location.href='personal_questionnaire.jsp'\"><font style='font-size:14px;'>需求问卷</font></td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"30px\" rowspan=\"10\" style=\"border-right:2px #0dad87 solid;\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\"><td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\"></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\"><td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\"><div class=\"triangle-left\" style=\"float:right\"></div></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"49px\"><td class=\"textR\" style=\"padding-top:15px;padding-bottom:15px;\"></td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"textL\" width=\"46%\">\r\n");
      out.write("\t\t\t\t<div style=\"background: #FFFFFF; width: 100%;padding-top:30px;\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\" style=\"border-collapse:separate;border-spacing:30px;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>邀请同事加入招聘团队</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style='font-size:14px;color:#4F4F4F;'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t发送邀请邮件给指定邮箱，被邀请人成功注册账号后既可使用U-offer\r\n");
      out.write("\t\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><font style='font-size:14px;color:#4F4F4F;'>输入同事邮箱</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"padding:0px 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"tongshiEmail\" class=\"form-control\" type=\"text\" style=\"width:200px !important;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr height=\"60px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"padding:0px 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" style=\"color:#FFF;background:#00B389;width:200px;\" onclick=\"sendemil()\">发送邀请</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"height:1px;background:#999999;\" colspan=\"3\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td rowspan=\"2\"/>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div style=\"background: #FFFFFF; width: 100%;min-height:300px;padding:0px 30px;\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\" id=\"message\">\r\n");
      out.write("\t\t\t\t\t\t<tr height=\"40px\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"6\" valign=\"top\">团队成员</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"gray textC\" style=\"background:#E2E2E2;\">姓名</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"gray textC\" style=\"background:#E2E2E2;\">职位</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"gray textC\" style=\"background:#E2E2E2;\">邮箱</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"gray textC\" style=\"background:#E2E2E2;\">身份</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"gray textC\" style=\"background:#E2E2E2;\">状态</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"gray textC\" style=\"background:#E2E2E2;\">操作</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"gray textC\">王工</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"gray textC\">HR</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"gray textC\">123234@dfsf.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"gray textC\">管理员</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"gray textC\">启用中</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"gray textC\"><font color=\"00B38A\">王工</font></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr height=\"30px\"/>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div style=\"width:100%;height:48%;\"></div>\r\n");
      out.write("\t<table style=\"width:100%;height:81px;background:#32373C;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"textC\">\r\n");
      out.write("\t\t\t\t<font color=\"#F5F8F9\" style=\"font-size:14px;white-space: nowrap;\">\r\n");
      out.write("\t\t\t\t\t关于我们&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t使用攻略&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t法律声明&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t关注我们\r\n");
      out.write("\t\t\t\t</font>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
