/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-05-15 06:49:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class mainfinduser_005fsum_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1494475596723L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>My JSP 'index.jsp' starting page</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../css/base.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../skins/all.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- <link href=\"../css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\" /> -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../img/title.ico\" type=\"image/x-icon\"/>\r\n");
      out.write("<style>\r\n");
      out.write("\t.btn.dropdown-toggle{\r\n");
      out.write("\t\tbackground:#CCCCCC;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxfileupload.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxSubmit.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- <script src=\"../js/Carousel.js\"></script> -->\r\n");
      out.write("<script src=\"../js/jquery.icheck.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.min.js\"></script>\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"../js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/locales/bootstrap-datetimepicker.zh-CN.js\"></script> -->\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction upload() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"register/firm.do\", // 自行按需配置好完整的url，包括ip和端口号  \r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdatatype : \"text\",\r\n");
      out.write("\t\t\tdata : JSON.stringify($(\"#form1\").serializeObject()),\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//头部\r\n");
      out.write("\tfunction changeColor1(der){\r\n");
      out.write("\t\tder.style.background=\"#777777\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor2(der){\r\n");
      out.write("\t\tder.style.background=\"#32373C\";\r\n");
      out.write("\t}\r\n");
      out.write("\tjQuery(function($){\r\n");
      out.write("\t\t$(\".dropdown .form-control\").click(function(){\r\n");
      out.write("\t\t\tif(this.parentNode.getElementsByTagName(\"button\") == undefined){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tthis.parentNode.getElementsByTagName(\"button\")[0].click();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction init(){\r\n");
      out.write("\t\tdocument.getElementById('allorpair').value = parent.document.getElementById('allorpair').value;\r\n");
      out.write("\t\tdocument.getElementById('firstIn').value = parent.document.getElementById('firstIn').value;\r\n");
      out.write("\t\tdocument.getElementById('pageId').value = parent.document.getElementById('pageId').value;\r\n");
      out.write("\t\tvar\turl = \"firm/findusersum1.do\";\r\n");
      out.write("\t\tvar formId = \"findusersumForm\";\r\n");
      out.write("\t\tvar data = ajaxSumbit(url, formId);\r\n");
      out.write("\t\tadddiv(data);\r\n");
      out.write("\t\taddpageNum(data.pageNum, \"u1\");\r\n");
      out.write("\t\tparent.document.getElementById('dataNum').innerText = data.dataNum;\r\n");
      out.write("\t\taddallorpair(data.allnum,data.pairnum);\r\n");
      out.write("\t\tparent.document.getElementById(\"iframe1\").height=0;\r\n");
      out.write("\t\tparent.document.getElementById(\"iframe1\").height=document.body.scrollHeight;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction addpageNum(items, u1){\r\n");
      out.write("\t\tvar inn = \"<ul class='pagination' id='u1' style='margin-top:10px;'>\";\r\n");
      out.write("\t\tvar pageId = parent.document.getElementById(\"pageId\").value;\r\n");
      out.write("\t\tif (items > 1) {\r\n");
      out.write("\t\t\tinn += \"<li><a href='#' onclick='getpage(1)'>&laquo;</a></li>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (items == 1) {\r\n");
      out.write("\t\t\tinn += \"<li><a href='#' onclick='getpage(1)'>1</a></li>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\tfor (var i = 0; i < items; i++) {\r\n");
      out.write("\t\t\t\tinn += \"<li><a href='#' onclick='getpage(\" + (i + 1) + \")'>\" + (i + 1) + \"</a></li>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tinn += \"</ul>\";\r\n");
      out.write("\t\tparent.document.getElementById(u1).innerHTML=inn;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction addallorpair(allnum,pairnum){\r\n");
      out.write("\t\tparent.document.getElementById('divall').innerHTML=\"<font style='font-size:14px;' color='#4F4F4F'>全部（\"+allnum+\")</font>\";\r\n");
      out.write("\t\tparent.document.getElementById('divpair').innerHTML=\"<font style='font-size:14px;' color='#4F4F4F'>已收藏（\"+pairnum+\")</font>\";\r\n");
      out.write("\t}\r\n");
      out.write("\t/* function addbutton(name,items,buttonId){\r\n");
      out.write("\t\tvar inn = \"\";\r\n");
      out.write("\t\tfor(var i in items){\r\n");
      out.write("\t\t\tinn = inn + \"<button type='button' class='close' aria-hidden='true' style='float:left;opacity:0.9;background:#00B38A;color:#FFF;padding:10px;'>\"\r\n");
      out.write("\t\t\t\t+\"<font size='2' style='font-weight: normal;letter-spacing:2px;'>\" + items[i].value \r\n");
      out.write("\t\t\t\t+\"<a href='#' id='\"+name+\"_\"+items[i].id+\"' onclick='removebutton(this)' style='color:#FFF;'>&nbsp;&nbsp;&times;</a></font></button>\";\r\n");
      out.write("\t\t\t\tparent.document.getElementById(name).value = items[i].id + \"_\" + items[i].value;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tparent.document.getElementById(buttonId).innerHTML=inn;\r\n");
      out.write("\t} */\r\n");
      out.write("\tfunction checkunderfined(eles){\r\n");
      out.write("\t\tif(eles != undefined){\r\n");
      out.write("\t\t\treturn eles.value;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction color1(obj){\r\n");
      out.write("\t\tif(obj.name != undefined){\r\n");
      out.write("\t\t\tif(obj.name.indexOf(\"had\") > -1){\r\n");
      out.write("\t\t\t\tdocument.getElementById(obj.name).src=\"../img/hadfeel.png\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(obj.name.indexOf(\"no\") > -1){\r\n");
      out.write("\t\t\t\tdocument.getElementById(obj.name).src=\"../img/nofeel.png\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tobj.style.color=\"#FFF\";\r\n");
      out.write("\t\tobj.style.border=\"1px #00B38A solid\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction color2(obj){\r\n");
      out.write("\t\tif(obj.name != undefined){\r\n");
      out.write("\t\t\tif(obj.name.indexOf(\"had\") > -1){\r\n");
      out.write("\t\t\t\tdocument.getElementById(obj.name).src=\"../img/collection.png\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(obj.name.indexOf(\"no\") > -1){\r\n");
      out.write("\t\t\t\tdocument.getElementById(obj.name).src=\"../img/delete.png\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tobj.style.color=\"#9A9A9A\";\r\n");
      out.write("\t\tobj.style.border=\"1px #CCCCCC solid\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction color3(obj){\r\n");
      out.write("\t\tobj.style.border=\"1px #57B1ED solid\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction color4(obj){\r\n");
      out.write("\t\tobj.style.border=\"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction adddiv(data){\r\n");
      out.write("\t\tvar div1 = \"\";\r\n");
      out.write("\t\tfor(var i in data.userresume){\r\n");
      out.write("\t\t\tvar item = data.userresume[i];\r\n");
      out.write("\t\t\tdiv1 = div1+\"<div class='getColor' tabindex='0' style='width:100%;cursor:pointer;' onmouseover='color3(this)' onmouseout='color4(this)' >\"//onclick='goView(\\\"\"+item.id+\"\\\")'\r\n");
      out.write("\t\t\t\t+\"<table style=' width: 100%;padding-top:5px;padding-left:10px;'>\" \r\n");
      out.write("\t\t\t\t\t\t\t+\"<tr height='40px'/>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+\"<td rowspan='5' width='150px' width='151px' style='padding-right:31px;'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+\"<img src=\" + item.photopath + \" onclick='goView(\\\"\"+item.id+\"\\\")' width='120px' height='120px'/>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+\"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+\"<td width='69%'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+\"<font  style='font-size:20px;color:#4F4F4F;'>\" + item.username + \"</font>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+\"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+\"<td/>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+\"<td class='textL' style='padding-right:25%;'><font style='font-size:14px;' color='#4F4F4F'>\" + item.nowyearwages + \"</font></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+\"<td class='textR' rowspan='2' width='20%'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+\"<table width='100%'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+\"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+\"<td width='50%' class='textR' style='padding-left:5px;'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+\"<div class='btn-group btn-group-lg'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+\"<button type='button' class='btn btn-default' name='nofeel\"+item.id+\"' onclick='nofeel(\\\"\"+item.id+\"\\\")' onmouseover='color1(this)' onmouseout='color2(this)' style='width: 120px;color:#9A9A9A;border:1px #CCCCCC solid;'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+\"<center><img src='../img/delete.png' width='16px' height='16px' id='nofeel\"+item.id+\"' />\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+\"<font style='font-size:14px;'>&nbsp;不感兴趣</font></center>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+\"</button>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+\"</div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+\"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+\"<td width='50%' class='textL' style='padding-left:5px;'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+\"<div class='btn-group btn-group-lg'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+\"<button id='regit' type='button' class='btn btn-default' name='hadfeel\"+item.id+\"' onclick='hadfeel(\\\"\"+item.id+\"\\\")' onmouseover='color1(this)' onmouseout='color2(this)' style='width:120px;color:#9A9A9A;border:1px #CCCCCC solid;'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+\"<center><img src='../img/collection.png' width='16px' height='16px' id='hadfeel\"+item.id+\"'/>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+\"<font style='font-size:14px;'>&nbsp;&nbsp;收藏</font></center>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+\"</button>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+\"</div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+\"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+\"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+\"</table>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+\"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t//+\"<tr height='20px'/>\"\r\n");
      out.write("// \t\t\t\t\t\t\t+\"<tr>\"//职位：\r\n");
      out.write("// \t\t\t\t\t\t\t\t+\"<td class='textL'><font size='1' color='#999999'></font><font size='1'>\" + item.resume + \"</font></td>\"\r\n");
      out.write("// \t\t\t\t\t\t\t\t+\"<td/>\"\r\n");
      out.write("// \t\t\t\t\t\t\t+\"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"<tr>\"//工作说明：\r\n");
      out.write("\t\t\t\t\t\t\t+\"<td class='textL' style='padding-right:25%;'><font style='font-size:14px;' color='#CCCCCC'></font><font style='font-size:14px;' color='#4F4F4F'>\" + item.jobDescript.substring(0, 115) + \"</font></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"<td/>\"\r\n");
      out.write("\t\t\t\t\t\t+\"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t+\"<tr>\"//公司：\r\n");
      out.write("\t\t\t\t\t\t\t+\"<td class='textL' style='padding-right:25%;'><font style='font-size:14px;' color='#CCCCCC'></font><font style='font-size:14px;' color='#4F4F4F'>\" + item.oldFirmName + \"</font></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"<td/>\"\r\n");
      out.write("\t\t\t\t\t\t+\"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"<tr>\"//学校：\r\n");
      out.write("\t\t\t\t\t\t\t\t+\"<td class='textL' style='padding-right:25%;'><font style='font-size:14px;' color='#4F4F4F'></font><font style='font-size:14px;' color='#4F4F4F'>\" + (item.xueli == '' ? '' : item.xueli + \"，\") + item.school + \"</font></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+\"<td/>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"<tr height='39px'/>\"\r\n");
      out.write("\t\t\t\t\t\t+\"</table>\"\r\n");
      out.write("\t\t\t\t\t+\"</div>\"\r\n");
      out.write("\t\t\t\t\t+\"<hr/>\";\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\tdocument.body.innerHTML=div1;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction nofeel(id) {//不感兴趣\r\n");
      out.write("\t\tvar url = \"firm/selectfindusersum1.do?status=0&offerCandidateId=\" + id;//状态（0：不敢兴趣，1：收藏）\r\n");
      out.write("\t\tvar formId = \"findusersumForm\";\r\n");
      out.write("\t\tvar data = ajaxSumbit(url, formId);\r\n");
      out.write("\t\tif(data == 'success'){\r\n");
      out.write("\t\t\talert(\"下次不再为您提供该候选人信息\");\r\n");
      out.write("\t\t\twindow.location.href=\"mainfinduser_sum.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction hadfeel(id) {//收藏\r\n");
      out.write("\t\tvar url = \"firm/selectfindusersum1.do?status=1&offerCandidateId=\" + id;//状态（0：不敢兴趣，1：收藏）\r\n");
      out.write("\t\tvar formId = \"findusersumForm\";\r\n");
      out.write("\t\tvar data = ajaxSumbit(url, formId);\r\n");
      out.write("\t\tif(data == 'success'){\r\n");
      out.write("\t\t\talert(\"收藏成功\");\r\n");
      out.write("\t\t\twindow.location.href=\"mainfinduser_sum.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goView(id){\r\n");
      out.write("\t\tvar url = \"login/sessionPutUser.do\";\r\n");
      out.write("\t\tvar data = ajaxSumbitNoform(url, id);\r\n");
      out.write("\t\ttop.location.href='resume_view.jsp';\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\t.getColor{\r\n");
      out.write("\t\tbackground-color:#FFF;\r\n");
      out.write("\t}\r\n");
      out.write("\t.getTdColor{\r\n");
      out.write("\t\tbackground-color:#00B38A;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t.getTdColor:focus{\r\n");
      out.write("\t\tbackground-color:#FFF;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t.getTdColor:hover{\r\n");
      out.write("\t\tbackground-color:#FFF;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\t<form id=\"findusersumForm\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"pageId\" name=\"pageId\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"citybutton\" name=\"citybutton\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"jobbutton\" name=\"jobbutton\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"workbutton\" name=\"workbutton\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"allorpair\" name=\"allorpair\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"firmsaved\" name=\"firmsaved\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"firstIn\" name=\"firstIn\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("<body onload=\"init()\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
