/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-05-15 03:31:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class user_005faccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1494475596723L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>My JSP 'index.jsp' starting page</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../css/base.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../skins/all.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- <link href=\"../css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\" /> -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../img/title.ico\" type=\"image/x-icon\"/>\r\n");
      out.write("<style>\r\n");
      out.write("\t.btn.dropdown-toggle{\r\n");
      out.write("\t\tbackground:#CCCCCC;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxfileupload.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxSubmit.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- <script src=\"../js/Carousel.js\"></script> -->\r\n");
      out.write("<script src=\"../js/jquery.icheck.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.min.js\"></script>\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"../js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/locales/bootstrap-datetimepicker.zh-CN.js\"></script> -->\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction upload() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"register/firm.do\", // 自行按需配置好完整的url，包括ip和端口号  \r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdatatype : \"text\",\r\n");
      out.write("\t\t\tdata : JSON.stringify($(\"#form1\").serializeObject()),\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//头部\r\n");
      out.write("\tfunction changeColor1(der){\r\n");
      out.write("\t\tder.style.background=\"#777777\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor2(der){\r\n");
      out.write("\t\tder.style.background=\"#32373C\";\r\n");
      out.write("\t}\r\n");
      out.write("\tjQuery(function($){\r\n");
      out.write("\t\t$(\".dropdown .form-control\").click(function(){\r\n");
      out.write("\t\t\tif(this.parentNode.getElementsByTagName(\"button\") == undefined){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tthis.parentNode.getElementsByTagName(\"button\")[0].click();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction init(){\r\n");
      out.write("\t\tvar url = \"login/useraccount1.do\";\r\n");
      out.write("\t\tvar formId = \"finduserForm\";\r\n");
      out.write("\t\tvar data = ajaxSumbit(url, formId);\r\n");
      out.write("\t\taddinformation(data.information);\r\n");
      out.write("\t\tdocument.getElementById(\"offerCandidateId\").value=data.offerCandidateId;\r\n");
      out.write("\t\tdocument.getElementById(\"firmguwen\").value=data.firmguwen;\r\n");
      out.write("\t\tdocument.getElementById(\"firmguwenValue\").value=data.firmguwenValue;\r\n");
      out.write("\t\taddLi(data.guwen,\"guwen\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction addinformation(item){\r\n");
      out.write("\t\tdocument.getElementById(\"userPhoto\").src=item.userPhoto;\r\n");
      out.write("\t\tdocument.getElementById(\"userName\").innerText=item.userName;\r\n");
      out.write("\t\tdocument.getElementById(\"usershenfen\").innerText=item.usershenfen;\r\n");
      out.write("\t\tdocument.getElementById(\"zhucetime\").innerText=item.zhucetime;\r\n");
      out.write("\t\tdocument.getElementById(\"newtime\").innerText=item.newtime;\r\n");
      out.write("\t\t//document.getElementById(\"firmName\").innerText=item.firmName;\r\n");
      out.write("\t\tdocument.getElementById(\"job\").innerText=item.job;\r\n");
      out.write("\t\tdocument.getElementById(\"phone\").innerText=item.phone;\r\n");
      out.write("\t\tdocument.getElementById(\"tongzhi\").innerText=item.tongzhi;\r\n");
      out.write("\t\tdocument.getElementById(\"status\").innerText=item.status;\r\n");
      out.write("\t\tdocument.getElementById(\"gewenbeizhu\").innerText=item.beizhu;\r\n");
      out.write("\t\tdocument.getElementById(\"beizhu\").value=item.beizhu;\r\n");
      out.write("\t}\r\n");
      out.write("\t//下拉列表\r\n");
      out.write("\tfunction addLi(items,liId){\r\n");
      out.write("\t\tvar inn = \"\";\r\n");
      out.write("\t\tfor(var i in items){\r\n");
      out.write("\t\t\tinn = inn + \"<li role='presentation'>\"\r\n");
      out.write("\t\t\t\t+\"<a role='menuitem' onclick='selectDownValue(\" + items[i].id +\",\\\"\" + items[i].value +\"\\\",\\\"\"+liId+\"\\\")'><font color='#000'>\" + items[i].value\r\n");
      out.write("\t\t\t\t+\"</font></a></li>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(liId).innerHTML=inn;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction selectDownValue(ke, val, targetInput){\r\n");
      out.write("\t\tvar ti1 = \"firm\" + targetInput;\r\n");
      out.write("\t\tvar ti2 = \"firm\" + targetInput + \"Value\";\r\n");
      out.write("\t\tdocument.getElementById(ti1).value=ke;\r\n");
      out.write("\t\tdocument.getElementById(ti2).value=val;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction validateCode() {\r\n");
      out.write("\t\tvar firmguwen = document.getElementById('firmguwen').value;\r\n");
      out.write("\t\tvar beizhu = document.getElementById('beizhu').value;\r\n");
      out.write("\t\tvar url = \"firm/changeUserStatus.do?firmguwen=\"+firmguwen+\"&beizhu=\"+beizhu;\r\n");
      out.write("\t\tvar formId = \"finduserForm\";\r\n");
      out.write("\t\tvar data = ajaxSumbit(url, formId);\r\n");
      out.write("\t\tif(data == \"success\"){\r\n");
      out.write("\t\t\talert(\"提交成功!\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"保存出错!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\twindow.location.href=\"user_account.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body bgcolor=\"#FFF\" onload=\"init()\">\r\n");
      out.write("\t<form id=\"finduserForm\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"offerCandidateId\" id=\"offerCandidateId\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div style=\"width:100%;padding:60px 14%;\">\r\n");
      out.write("\t\t<table width=\"563px\" style=\"border-bottom:2px #CCCCCC solid;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"width:130px;\" rowspan=\"3\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../img/changjinglu.jpg\" width=\"120px\" height=\"120px\" id=\"userPhoto\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td valign=\"bottom\" style=\"padding-left:40px;\">\r\n");
      out.write("\t\t\t\t\t<font style=\"font-size:14px;\" color=\"#4F4F4F\" id=\"userName\">捂脸</font>\r\n");
      out.write("\t\t\t\t\t<font style=\"font-size:14px;\" color=\"#3CBAFF\" id=\"usershenfen\">管理员</font>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td valign=\"bottom\" style=\"height:25px;padding-left:40px;\">\r\n");
      out.write("\t\t\t\t\t<font style=\"font-size:14px;\" color=\"#4F4F4F\" id=\"zhucetime\">注册时间：1017年07月17日</font>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td valign=\"top\" style=\"height:15px;padding-left:40px;\">\r\n");
      out.write("\t\t\t\t\t<font style=\"font-size:14px;\" color=\"#4F4F4F\" id=\"newtime\">最新登陆：1017年07月17日</font>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t <td height=\"49px\" colspan=\"2\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table width=\"563px\" style=\"border-bottom:2px #CCCCCC solid;\" cellpadding=\"10\">\r\n");
      out.write("\t\t\t<tr height=\"38px\"/>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"100px\" style=\"padding-bottom:30px;\"><font style=\"font-size:14px;\" color=\"#4F4F4F\">期望职位</font></td>\r\n");
      out.write("\t\t\t\t<td style=\"padding-bottom:30px;\"><font style=\"font-size:14px;\" color=\"#3CBAFF\" id=\"job\">CEO</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"100px\" style=\"padding-bottom:30px;\"><font style=\"font-size:14px;\" color=\"#4F4F4F\">手机</font></td>\r\n");
      out.write("\t\t\t\t<td style=\"padding-bottom:30px;\"><font style=\"font-size:14px;\" color=\"#3CBAFF\" id=\"phone\">133464356</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"100px\" style=\"padding-bottom:30px;\"><font style=\"font-size:14px;\" color=\"#4F4F4F\">通知信息</font></td>\r\n");
      out.write("\t\t\t\t<td style=\"padding-bottom:30px;\"><font style=\"font-size:14px;\" color=\"#3CBAFF\" id=\"tongzhi\">已开启：邮件通知，邮件订阅</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"100px\" style=\"padding-bottom:30px;\"><font style=\"font-size:14px;\" color=\"#4F4F4F\">目前状态</font></td>\r\n");
      out.write("\t\t\t\t<td style=\"padding-bottom:30px;\"><font style=\"font-size:14px;\" color=\"#FE9B00\" id=\"status\">审核中</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"100px\" style=\"padding-bottom:30px;\"><font style=\"font-size:14px;\" color=\"#4F4F4F\">顾问备注</font></td>\r\n");
      out.write("\t\t\t\t<td id=\"gewenbeizhu\" style=\"padding-bottom:30px;font-size:14px;color:#4F4F4F;\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table width=\"541px\" style=\"border-collapse:separate;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"541px\" style=\"padding:25px 0px;\"><font style=\"font-size:14px;\" color=\"#4F4F4F\">顾问审核</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"49px\">\r\n");
      out.write("\t\t\t\t<td style=\"padding-bottom:28px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\" style=\"display:inline;width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"firmguwen\" name=\"firmguwen\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"firmguwenValue\" id=\"firmguwenValue\" class=\"form-control\" readOnly=\"readOnly\" style=\"width: 120px !important;color:#9A9A9A;font-size:14px;\">\r\n");
      out.write("\t\t\t\t\t\t    <button type=\"button\" style=\"width:41px;height:41px !important;background-color:#3CBAFF;color:#FFF;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu1\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t        <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t\t\t    <ul class=\"dropdown-menu\" role=\"menu\" aria-labelledby=\"dropdownMenu1\" style=\"width: 120px !important\" id=\"guwen\">\r\n");
      out.write("\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t    </ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"padding-bottom:28px;\">\r\n");
      out.write("\t\t\t\t\t<textarea placeholder=\"顾问审核备注\" rows=\"8\" style=\"width:541px;font-size:14px;color:#4F4F4F;height:181px;\" id=\"beizhu\" name=\"beizhu\"></textarea>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"textR\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"validateCode()\" data-toggle=\"button\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-color: #3CBAFF; border-color: #3CBAFF; color:#FFF; width: 150px;\">\r\n");
      out.write("\t\t\t\t\t\t提交</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width:100%;height:180px;\"></div>\r\n");
      out.write("\t<table style=\"width:100%;height:81px;background:#32373C;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"textC\">\r\n");
      out.write("\t\t\t\t<font color=\"#F5F8F9\" style=\"font-size:14px;white-space: nowrap;\">\r\n");
      out.write("\t\t\t\t\t关于我们&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t使用攻略&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t法律声明&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t关注我们\r\n");
      out.write("\t\t\t\t</font>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
